In [5]:
import pandas as pd

In [6]:
import numpy as np

In [13]:
a = np.array([1,0,1])
b = np.array([[1],[0],[1]])

In [15]:
a*b

array([[1, 0, 1],
       [0, 0, 0],
       [1, 0, 1]])

In [16]:
b*a

array([[1, 0, 1],
       [0, 0, 0],
       [1, 0, 1]])

In [18]:
np.dot(a,b)

array([2])

In [21]:
#np.cross(a,b)
#get error